# Site settings
title: mayask
header-img: img/home-bg.jpg
email: max@mayask.me
copyright_name: Maxim Yaskevich
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://blog.mayask.me"
twitter_username: mayaskme
github_username: myaskevich
# facebook_username:  StartBootstrap
email_username: max@mayask.me

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
