# Site settings
title: mayask
header-img: img/home-bg.jpg
email: max@mayask.me
copyright_name: Maxim Yaskevich
description: "Maxim Yaskevich Personal Blog"
baseurl: ""
url: "http://blog.mayask.me"
twitter_username: mayaskme
github_username: myaskevich

google_tracking_id: UA-107791293-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
